/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/timofun/Documents/project/note/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-4850c630",
    path: "/engineered.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4850c630").then(next)
    },
  },
  {
    name: "v-74c15a3a",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74c15a3a").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-0b8af578",
    path: "/mac.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0b8af578").then(next)
    },
  },
  {
    name: "v-2af562d8",
    path: "/git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2af562d8").then(next)
    },
  },
  {
    name: "v-2ace94f2",
    path: "/js.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ace94f2").then(next)
    },
  },
  {
    name: "v-2230a496",
    path: "/mini.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2230a496").then(next)
    },
  },
  {
    name: "v-5c314450",
    path: "/order.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c314450").then(next)
    },
  },
  {
    name: "v-15202a90",
    path: "/react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15202a90").then(next)
    },
  },
  {
    name: "v-177357f8",
    path: "/css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-177357f8").then(next)
    },
  },
  {
    name: "v-21b91a18",
    path: "/flutter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21b91a18").then(next)
    },
  },
  {
    name: "v-017e68ec",
    path: "/optimize.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-017e68ec").then(next)
    },
  },
  {
    name: "v-2d0171cc",
    path: "/webstorm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d0171cc").then(next)
    },
  },
  {
    name: "v-fa273550",
    path: "/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fa273550").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]