/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Note文档",
  "description": "平时随手记录文档",
  "base": "/note/",
  "headTags": [
    [
      "link",
      {
        "rel": "manifest",
        "href": "/note/manifest.json"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#5a8dff"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileColor",
        "content": "#000000"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": null,
        "actionText": "前端 Note →",
        "actionLink": "/js.html",
        "features": [
          {
            "title": "Js"
          },
          {
            "title": "Vue"
          },
          {
            "title": "React"
          },
          {
            "title": "Flutter"
          }
        ],
        "footer": "MIT Licensed | Copyright @2020-present timofun"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-74c15a3a",
      "path": "/"
    },
    {
      "title": "Css 相关",
      "frontmatter": {},
      "regularPath": "/css.html",
      "relativePath": "css.md",
      "key": "v-177357f8",
      "path": "/css.html"
    },
    {
      "title": "工程化 相关",
      "frontmatter": {},
      "regularPath": "/engineered.html",
      "relativePath": "engineered.md",
      "key": "v-4850c630",
      "path": "/engineered.html"
    },
    {
      "title": "Git 相关",
      "frontmatter": {},
      "regularPath": "/git.html",
      "relativePath": "git.md",
      "key": "v-2af562d8",
      "path": "/git.html",
      "headers": [
        {
          "level": 2,
          "title": "push报错",
          "slug": "push报错"
        },
        {
          "level": 2,
          "title": "GitHook 工具 —— husky 配置",
          "slug": "githook-工具-husky-配置"
        }
      ]
    },
    {
      "title": "Js 相关",
      "frontmatter": {},
      "regularPath": "/js.html",
      "relativePath": "js.md",
      "key": "v-2ace94f2",
      "path": "/js.html"
    },
    {
      "title": "Flutter 相关",
      "frontmatter": {},
      "regularPath": "/flutter.html",
      "relativePath": "flutter.md",
      "key": "v-21b91a18",
      "path": "/flutter.html",
      "headers": [
        {
          "level": 2,
          "title": "升级CocoaPods到最新版本",
          "slug": "升级cocoapods到最新版本"
        },
        {
          "level": 2,
          "title": "pod install报错LibreSSL SSLconnect: SSLERROR_SYSCALL in connection to github.com:443",
          "slug": "pod-install报错libressl-ssl-connect-ssl-error-syscall-in-connection-to-github-com-443"
        },
        {
          "level": 3,
          "title": "解决方式1",
          "slug": "解决方式1"
        },
        {
          "level": 3,
          "title": "解决方式2",
          "slug": "解决方式2"
        }
      ]
    },
    {
      "title": "Mac 相关",
      "frontmatter": {},
      "regularPath": "/mac.html",
      "relativePath": "mac.md",
      "key": "v-0b8af578",
      "path": "/mac.html",
      "headers": [
        {
          "level": 2,
          "title": "Mac上看不到.git目录的解决方法",
          "slug": "mac上看不到-git目录的解决方法"
        },
        {
          "level": 2,
          "title": "Mac 刷新dns缓存",
          "slug": "mac-刷新dns缓存"
        },
        {
          "level": 2,
          "title": "Mac 美化终端",
          "slug": "mac-美化终端"
        },
        {
          "level": 2,
          "title": "Mac 微信插件",
          "slug": "mac-微信插件"
        },
        {
          "level": 3,
          "title": "安装 Oh My WeChat",
          "slug": "安装-oh-my-wechat"
        },
        {
          "level": 2,
          "title": "Npm源管理器Nrm使用",
          "slug": "npm源管理器nrm使用"
        },
        {
          "level": 3,
          "title": "1.安装:",
          "slug": "_1-安装"
        },
        {
          "level": 3,
          "title": "2.列出可选择的源:",
          "slug": "_2-列出可选择的源"
        },
        {
          "level": 3,
          "title": "3.切换使用的源:",
          "slug": "_3-切换使用的源"
        },
        {
          "level": 3,
          "title": "4.添加一个源: nrm add",
          "slug": "_4-添加一个源-nrm-add"
        },
        {
          "level": 3,
          "title": "5.删除一个源:nrm del",
          "slug": "_5-删除一个源-nrm-del"
        },
        {
          "level": 3,
          "title": "6.测试源速度:nrm test",
          "slug": "_6-测试源速度-nrm-test"
        },
        {
          "level": 3,
          "title": "7.不使用nrm来切换源",
          "slug": "_7-不使用nrm来切换源"
        },
        {
          "level": 3,
          "title": "8.访问源的主页",
          "slug": "_8-访问源的主页"
        }
      ]
    },
    {
      "title": "小程序 相关",
      "frontmatter": {},
      "regularPath": "/mini.html",
      "relativePath": "mini.md",
      "key": "v-2230a496",
      "path": "/mini.html"
    },
    {
      "title": "优化",
      "frontmatter": {},
      "regularPath": "/optimize.html",
      "relativePath": "optimize.md",
      "key": "v-017e68ec",
      "path": "/optimize.html"
    },
    {
      "title": "其它",
      "frontmatter": {},
      "regularPath": "/order.html",
      "relativePath": "order.md",
      "key": "v-5c314450",
      "path": "/order.html",
      "headers": [
        {
          "level": 2,
          "title": "markdown语法",
          "slug": "markdown语法"
        }
      ]
    },
    {
      "title": "Vue 相关",
      "frontmatter": {},
      "regularPath": "/vue.html",
      "relativePath": "vue.md",
      "key": "v-fa273550",
      "path": "/vue.html"
    },
    {
      "title": "React 相关",
      "frontmatter": {},
      "regularPath": "/react.html",
      "relativePath": "react.md",
      "key": "v-15202a90",
      "path": "/react.html"
    },
    {
      "title": "Webstorm 相关",
      "frontmatter": {},
      "regularPath": "/webstorm.html",
      "relativePath": "webstorm.md",
      "key": "v-2d0171cc",
      "path": "/webstorm.html",
      "headers": [
        {
          "level": 2,
          "title": "webstorm全局搜索搜不到内容",
          "slug": "webstorm全局搜索搜不到内容"
        },
        {
          "level": 2,
          "title": "Git 忽略.idea/workspace.xml文件",
          "slug": "git-忽略-idea-workspace-xml文件"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebar": [
      {
        "title": "Js",
        "collapsable": true,
        "path": "/js.md"
      },
      {
        "title": "Css",
        "collapsable": true,
        "path": "/css.md"
      },
      {
        "title": "Vue",
        "collapsable": true,
        "path": "/vue.md"
      },
      {
        "title": "React",
        "collapsable": true,
        "path": "/react.md"
      },
      {
        "title": "Flutter",
        "collapsable": true,
        "path": "flutter.md"
      },
      {
        "title": "小程序",
        "collapsable": true,
        "path": "/mini.md"
      },
      {
        "title": "工程化",
        "collapsable": true,
        "path": "/engineered.md"
      },
      {
        "title": "性能优化",
        "collapsable": true,
        "path": "/optimize.md"
      },
      {
        "title": "Git",
        "collapsable": true,
        "path": "/git.md"
      },
      {
        "title": "Webstorm",
        "collapsable": true,
        "path": "/webstorm.md"
      },
      {
        "title": "Mac",
        "collapsable": true,
        "path": "/mac.md"
      },
      {
        "title": "Order",
        "collapsable": true,
        "path": "/order.md"
      }
    ],
    "sidebarDepth": 1
  }
}