/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "精臣固定资产",
  "description": "让物的管理更简单",
  "base": "/handbook/",
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/home.png",
        "actionText": "快速上手 →",
        "actionLink": "/pc/summary.html",
        "features": [
          {
            "title": "帐实相符",
            "details": "一物一码，资产全生命周期管理"
          },
          {
            "title": "智能报表",
            "details": "多维度资产查询、统计"
          },
          {
            "title": "智能盘点",
            "details": "扫码/RFID盘点资产"
          }
        ],
        "footer": "Copyright © 2018-2020 武汉精臣智慧标识科技有限公司 | 鄂ICP备14016179号"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-a917738c",
      "path": "/"
    },
    {
      "title": "财务管理流程",
      "frontmatter": {},
      "regularPath": "/pc/finance.html",
      "relativePath": "pc/finance.md",
      "key": "v-9c9ce584",
      "path": "/pc/finance.html"
    },
    {
      "frontmatter": {
        "sidebar": false
      },
      "regularPath": "/pc/inventory.html",
      "relativePath": "pc/inventory.md",
      "key": "v-2b3bb73a",
      "path": "/pc/inventory.html"
    },
    {
      "frontmatter": {
        "sidebar": false
      },
      "regularPath": "/pc/emp_manage.html",
      "relativePath": "pc/emp_manage.md",
      "key": "v-bd477164",
      "path": "/pc/emp_manage.html",
      "headers": [
        {
          "level": 3,
          "title": "概述",
          "slug": "概述"
        },
        {
          "level": 3,
          "title": "登录",
          "slug": "登录"
        },
        {
          "level": 3,
          "title": "我的资产",
          "slug": "我的资产"
        },
        {
          "level": 3,
          "title": "自助盘点",
          "slug": "自助盘点"
        },
        {
          "level": 3,
          "title": "意见反馈",
          "slug": "意见反馈"
        },
        {
          "level": 3,
          "title": "分享小程序",
          "slug": "分享小程序"
        },
        {
          "level": 3,
          "title": "添加到我的小程序",
          "slug": "添加到我的小程序"
        },
        {
          "level": 3,
          "title": "关注公众号",
          "slug": "关注公众号"
        }
      ]
    },
    {
      "title": "耗材管理流程",
      "frontmatter": {},
      "regularPath": "/pc/consumable.html",
      "relativePath": "pc/consumable.md",
      "key": "v-5292f06e",
      "path": "/pc/consumable.html",
      "headers": [
        {
          "level": 2,
          "title": "系统基础信息设置",
          "slug": "系统基础信息设置"
        },
        {
          "level": 2,
          "title": "耗材管理基础信息设置",
          "slug": "耗材管理基础信息设置"
        },
        {
          "level": 3,
          "title": "1. 耗材分类",
          "slug": "_1-耗材分类"
        },
        {
          "level": 3,
          "title": "2. 仓库设置",
          "slug": "_2-仓库设置"
        },
        {
          "level": 3,
          "title": "3. 品牌设置",
          "slug": "_3-品牌设置"
        },
        {
          "level": 3,
          "title": "4. 供应商设置",
          "slug": "_4-供应商设置"
        },
        {
          "level": 2,
          "title": "新建耗材档案及标签打印",
          "slug": "新建耗材档案及标签打印"
        },
        {
          "level": 3,
          "title": "1. 新建耗材档案",
          "slug": "_1-新建耗材档案"
        },
        {
          "level": 3,
          "title": "2. 打印耗材标签",
          "slug": "_2-打印耗材标签"
        },
        {
          "level": 2,
          "title": "耗材入库",
          "slug": "耗材入库"
        },
        {
          "level": 2,
          "title": "耗材出库",
          "slug": "耗材出库"
        },
        {
          "level": 2,
          "title": "耗材数据查询",
          "slug": "耗材数据查询"
        },
        {
          "level": 3,
          "title": "1. 耗材存量查询",
          "slug": "_1-耗材存量查询"
        },
        {
          "level": 3,
          "title": "2. 耗材领用查询",
          "slug": "_2-耗材领用查询"
        },
        {
          "level": 3,
          "title": "3. 耗材出入库查询",
          "slug": "_3-耗材出入库查询"
        }
      ]
    },
    {
      "title": "资产管理流程",
      "frontmatter": {},
      "regularPath": "/pc/guide.html",
      "relativePath": "pc/guide.md",
      "key": "v-5a484dfa",
      "path": "/pc/guide.html",
      "headers": [
        {
          "level": 2,
          "title": "系统基础信息设置",
          "slug": "系统基础信息设置"
        },
        {
          "level": 3,
          "title": "1. 角色权限设置",
          "slug": "_1-角色权限设置"
        },
        {
          "level": 3,
          "title": "2. 添加子账号",
          "slug": "_2-添加子账号"
        },
        {
          "level": 3,
          "title": "3. 组织员工管理",
          "slug": "_3-组织员工管理"
        },
        {
          "level": 2,
          "title": "资产管理基础信息设置",
          "slug": "资产管理基础信息设置"
        },
        {
          "level": 3,
          "title": "1. 资产分类",
          "slug": "_1-资产分类"
        },
        {
          "level": 3,
          "title": "2. 区域管理",
          "slug": "_2-区域管理"
        },
        {
          "level": 3,
          "title": "3. 标签模板",
          "slug": "_3-标签模板"
        },
        {
          "level": 2,
          "title": "资产入库及标签打印",
          "slug": "资产入库及标签打印"
        },
        {
          "level": 3,
          "title": "1. 资产入库",
          "slug": "_1-资产入库"
        },
        {
          "level": 3,
          "title": "2. 打印资产标签",
          "slug": "_2-打印资产标签"
        },
        {
          "level": 2,
          "title": "资产管理",
          "slug": "资产管理"
        },
        {
          "level": 2,
          "title": "盘点管理",
          "slug": "盘点管理"
        },
        {
          "level": 2,
          "title": "数据报表",
          "slug": "数据报表"
        },
        {
          "level": 3,
          "title": "1. 首页资产统计概况",
          "slug": "_1-首页资产统计概况"
        },
        {
          "level": 3,
          "title": "2. 资产履历",
          "slug": "_2-资产履历"
        }
      ]
    },
    {
      "title": "系统其它功能",
      "frontmatter": {},
      "regularPath": "/pc/order.html",
      "relativePath": "pc/order.md",
      "key": "v-567af254",
      "path": "/pc/order.html",
      "headers": [
        {
          "level": 2,
          "title": "微信员工端",
          "slug": "微信员工端"
        },
        {
          "level": 2,
          "title": "打印机及耗材",
          "slug": "打印机及耗材"
        }
      ]
    },
    {
      "title": "概述",
      "frontmatter": {},
      "regularPath": "/pc/summary.html",
      "relativePath": "pc/summary.md",
      "key": "v-640d5cb4",
      "path": "/pc/summary.html",
      "headers": [
        {
          "level": 3,
          "title": "1. PC端",
          "slug": "_1-pc端"
        },
        {
          "level": 3,
          "title": "2. 移动端",
          "slug": "_2-移动端"
        }
      ]
    },
    {
      "title": "常见问题",
      "frontmatter": {},
      "regularPath": "/pc/q&a.html",
      "relativePath": "pc/q&a.md",
      "key": "v-26ee1a9a",
      "path": "/pc/q&a.html",
      "headers": [
        {
          "level": 2,
          "title": "组织设置",
          "slug": "组织设置"
        },
        {
          "level": 2,
          "title": "标签模版",
          "slug": "标签模版"
        },
        {
          "level": 2,
          "title": "角色权限设置",
          "slug": "角色权限设置"
        },
        {
          "level": 2,
          "title": "资产入库",
          "slug": "资产入库"
        },
        {
          "level": 2,
          "title": "资产管理",
          "slug": "资产管理"
        },
        {
          "level": 2,
          "title": "耗材管理",
          "slug": "耗材管理"
        },
        {
          "level": 2,
          "title": "标签打印",
          "slug": "标签打印"
        },
        {
          "level": 2,
          "title": "盘点管理",
          "slug": "盘点管理"
        },
        {
          "level": 2,
          "title": "其他问题",
          "slug": "其他问题"
        },
        {
          "level": 2,
          "title": "打印机",
          "slug": "打印机"
        },
        {
          "level": 2,
          "title": "PDA",
          "slug": "pda"
        },
        {
          "level": 2,
          "title": "耗材",
          "slug": "耗材"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/logo.png",
    "sidebar": [
      {
        "title": "概述",
        "collapsable": true,
        "path": "/pc/summary.md"
      },
      {
        "title": "资产管理流程",
        "collapsable": true,
        "path": "/pc/guide.md"
      },
      {
        "title": "耗材管理流程",
        "collapsable": true,
        "path": "/pc/consumable.md"
      },
      {
        "title": "财务管理流程",
        "collapsable": true,
        "path": "/pc/finance.md"
      },
      {
        "title": "系统其它功能",
        "collapsable": true,
        "path": "/pc/order.md"
      },
      {
        "title": "常见问题",
        "collapsable": true,
        "path": "/pc/q&a.md"
      }
    ],
    "sidebarDepth": 1
  }
}